all:	
	g++ -Wall -Og -g -Iobj_dir/ -I/usr/share/verilator/include -I/usr/share/verilator/include/vltstd /usr/share/verilator/include/verilated.cpp /usr/share/verilator/include/verilated_vcd_c.cpp axi_lite_master_tb.cpp obj_dir/Vaxi_lite_slave__ALL.a -o axi_lite_master_tb
